-- DROP TABLE IF EXISTS public.products CASCADE;
-- THIS CREATES THE TABLE IF "products" EXISTS

CREATE TABLE 
	IF NOT EXISTS
		products(
			id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
			name VARCHAR(50) NOT NULL,
			description VARCHAR (255) NOT NULL,
			brand VARCHAR(50) NOT NULL,
			image_url TEXT NOT NULL,
			price NUMERIC NOT NULL,
			category VARCHAR(50) NOT NULL,
			created_at TIMESTAMPTZ DEFAULT NOW(),
			updated_at TIMESTAMPTZ DEFAULT NOW()
);